---
- name: Run Ubuntu Tasks
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: Run Darwin Tasks
  ansible.builtin.import_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'
